server:
  port: 8081
spring:
  redis:
    host: 47.99.175.197
  cloud:
    nacos:
      discovery:
        server-addr: 47.99.175.197:8848
        namespace: cea83c1b-7a99-4bb1-8596-895a4faab520
  application:
    name: hdu-interrupt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lyh
    password: Lyh701721...
    url: jdbc:mysql://124.221.61.179:13306/hdu-interrupt?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
seata:
  service:
    vgroup-mapping:
      hdu-account-seata-service-group: default
      hdu-interrupt-seata-service-group: default
      hdu-fpga-seata-service-group: default
      hdu-record-seata-service-group: default
    grouplist:
      default: 47.99.175.197:8091
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://47.99.175.197:8848?register-consumer-url=true
    group: dubbo
    register-mode: interface
    parameters:
      namespace: c29600b0-2e5d-450b-bab0-e56d78292d51
  metadata-report:
    address: nacos://47.99.175.197:8848