server:
  port: 8082
spring:
  application:
    name: hdu-record
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lyh701721
    url: jdbc:mysql://localhost:3306/hdu-interrupt?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
seata:
  service:
    vgroup-mapping:
      hdu-account-seata-service-group: default
      hdu-interrupt-seata-service-group: default
    grouplist:
      default: 47.99.175.197:8091
dubbo:
  application:
    name: hdu-account
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://47.99.175.197:8848
    group: dubbo
rocketmq:
  name-server: 47.99.175.197:9876
  producer:
    group: hdu-record-group