server:
  port: 8080
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.99.175.197:8848
  application:
    name: hdu-account
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lyh701721
    url: jdbc:mysql://localhost:3306/hdu-interrupt?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
seata:
  service:
    vgroup-mapping:
      hdu-account-seata-service-group: default
      hdu-interrupt-seata-service-group: default
    grouplist:
      default: 47.99.175.197:8091