security:
  oauth2:
    sso:
      login-path: /toLogin
server:
  port: 9090
  servlet:
    context-path: /sso
    encoding:
      charset: UTF-8
spring:
  application:
    name: hdu-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lyh701721
    url: jdbc:mysql://localhost:3306/hdu-interrupt?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
seata:
  service:
    vgroup-mapping:
      hdu-account-seata-service-group: default
      hdu-interrupt-seata-service-group: default
      hdu-fpga-seata-service-group: default
      hdu-record-seata-service-group: default
      hdu-auth-seata-service-group: default
    grouplist:
      default: 47.99.175.197:8091
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://47.99.175.197:8848
    group: dubbo
    register-mode: interface
    parameters:
      namespace: c29600b0-2e5d-450b-bab0-e56d78292d51
  metadata-report:
    address: nacos://47.99.175.197:8848